package Gantry::Samples::AuthCookie::SQLite;

use strict;

use base 'Gantry::Samples';


#-----------------------------------------------------------------
# $self->do_main(  )
#-----------------------------------------------------------------
sub do_main {
    my ( $self ) = @_;
    
    $self->stash->view->title( 'Auth Cookie w/ SQLite' );
    $self->template( 'authcookie_sqlite.tt' );
    
} # END do_open

#-----------------------------------------------------------------
# $self->do_open(  )
#-----------------------------------------------------------------
sub do_open {
    my ( $self ) = @_;
    
    return( "you're in" );

} # END do_open

#-----------------------------------------------------------------
# $self->do_optional(  )
#-----------------------------------------------------------------
sub do_optional {
    my ( $self ) = @_;

    if ( $self->user ) {
        return ( "hey, I know you ... " . $self->user ); 
    }
    else {
        return( "don't know you, but you're in anyway" );
    }

    # remember you can also access $self->auth_user_row when a user is authed 

} # END do_open

1;

=head1 NAME

Gantry::Samples::AuthCookie::SQLite - A controller in the Gantry::Samples application

=head1 SYNOPSIS

This package is meant to be used in a stand alone server/CGI script or the
Perl block of an httpd.conf file.

Stand Alone Server or CGI script:

    use Gantry::Samples::AuthCookie::SQLite;

    my $cgi = Gantry::Engine::CGI->new( {
        config => {
            #...
        },
        locations => {
            '/someurl' => 'Gantry::Samples::AuthCookie::SQLite',
            #...
        },
    } );

httpd.conf:

    <Perl>
        # ...
        use Gantry::Samples::AuthCookie::SQLite;
    </Perl>

    <Location /someurl>
        SetHandler  perl-script
        PerlHandler Gantry::Samples::AuthCookie::SQLite
    </Location>

If all went well, one of these was correctly written during app generation.

=head1 DESCRIPTION

This module was originally generated by Bigtop.  But feel free to edit it.
You might even want to describe the table this module controls here.

=head1 METHODS

=over 4

=item do_open

=item do_closed

=item schema_base_class

=item get_orm_helper


=back


=head1 DEPENDENCIES

    Gantry::Samples

=head1 AUTHOR

Timotheus Keefer, E<lt>tkeefer@apple.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2007 Timotheus Keefer

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut
