package Gantry::Samples::Model::item;
use strict; use warnings;

use base 'Gantry::Utils::DBIxClass', 'Exporter';

use Gantry::Samples::Model::GEN::item;

our $ITEM = 'Gantry::Samples::Model::item';

our @EXPORT_OK = ( '$ITEM' );

1;

=head1 NAME

Gantry::Samples::Model::item - model for item table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Gantry::Utils::DBIxClass.  It was generated by Bigtop, but is
NOT subject to regeneration.

=head1 METHODS (mixed in from Gantry::Samples::Model::GEN::item)

You may use all normal Gantry::Utils::DBIxClass methods and the
ones listed here:

=over 4

=item get_foreign_display_fields

=item get_foreign_tables

=item foreign_display

=item table_name

=back

=cut
