package Gantry::Samples::Model::user_group;
use strict; use warnings;

use base 'Gantry::Utils::DBIxClass', 'Exporter';

use Gantry::Samples::Model::GEN::user_group;

our $USER_GROUP = 'Gantry::Samples::Model::user_group';

our @EXPORT_OK = ( '$USER_GROUP' );

1;

=head1 NAME

Gantry::Samples::Model::user_group - model for user_group table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Gantry::Utils::DBIxClass.  It was generated by Bigtop, but is
NOT subject to regeneration.

=head1 METHODS (mixed in from Gantry::Samples::Model::GEN::user_group)

You may use all normal Gantry::Utils::DBIxClass methods and the
ones listed here:

=over 4

=item get_foreign_display_fields

=item get_foreign_tables

=item foreign_display

=item table_name

=back

=cut
