package Gantry::Samples::Model::user_user_group;
use strict; use warnings;

use base 'Gantry::Utils::DBIxClass', 'Exporter';

use Gantry::Samples::Model::GEN::user_user_group;

our $USER_USER_GROUP = 'Gantry::Samples::Model::user_user_group';

our @EXPORT_OK = ( '$USER_USER_GROUP' );

1;

=head1 NAME

Gantry::Samples::Model::user_user_group - model for user_user_group table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Gantry::Utils::DBIxClass.  It was generated by Bigtop, but is
NOT subject to regeneration.

=cut
