package Gantry::Samples::AjaxRequest;

use strict;

use base 'Gantry::Samples';

#-----------------------------------------------------------------
# $self->do_main(  )
#-----------------------------------------------------------------
sub do_main {
    my ( $self ) = @_;

    $self->stash->view->title( 'AJAX Request' );
    $self->template( 'ajaxrequest.tt' );


} # END do_main

#-----------------------------------------------------------------
# $self->do_badcontent(  )
#-----------------------------------------------------------------
sub do_badcontent {
    my ( $self ) = @_;

    $self->status( '500' );
    return( 'Server Error' );

} # END do_badcontent

#-----------------------------------------------------------------
# $self->do_content(  )
#-----------------------------------------------------------------
sub do_content {
    my ( $self ) = @_;

    # disable wrapping
    $self->template_wrapper( 0 );

    return( '<b>' . localtime( time ) . "</b>" );

} # END do_content

#-----------------------------------------------------------------
# $self->do_version(  )
#-----------------------------------------------------------------
sub do_version {
    my ( $self ) = @_;

    # disable wrapping
    $self->template_wrapper( 0 );

    return( '<b> Gantry ' . $Gantry::VERSION . "</b>" );

} # END do_version


1;

=head1 NAME

Gantry::Samples::AjaxRequest - A controller in the Gantry::Samples application

=head1 SYNOPSIS

This package is meant to be used in a stand alone server/CGI script or the
Perl block of an httpd.conf file.

Stand Alone Server or CGI script:

    use Gantry::Samples::AjaxRequest;

    my $cgi = Gantry::Engine::CGI->new( {
        config => {
            #...
        },
        locations => {
            '/someurl' => 'Gantry::Samples::AjaxRequest',
            #...
        },
    } );

httpd.conf:

    <Perl>
        # ...
        use Gantry::Samples::AjaxRequest;
    </Perl>

    <Location /someurl>
        SetHandler  perl-script
        PerlHandler Gantry::Samples::AjaxRequest
    </Location>

If all went well, one of these was correctly written during app generation.

=head1 DESCRIPTION

This module was originally generated by Bigtop.  But feel free to edit it.
You might even want to describe the table this module controls here.

=head1 METHODS

=over 4

=item do_main

=item do_badcontent

=item do_content

=item do_version

=item schema_base_class

=item get_orm_helper


=back


=head1 DEPENDENCIES

    Gantry::Samples

=head1 AUTHOR

Timotheus Keefer, E<lt>tkeefer@apple.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2006 Timotheus Keefer

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut
